#配置dev环境
server:
  port: 8084

spring:
 profiles: dev
 application:
  name: provider-config
  #配置数据源
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn02?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
 jpa:
    generate-ddl: true
    show-sql: true
    hibernite:
      ddl-auto: none



eureka:
  client:
    service-url:
      defaultZone: http://eureka8400.com/eureka

---
#配置test环境
server:
  port: 8085

spring:
  profiles: test
  application:
    name: provider-config
  jpa:
  generate-ddl: true
  show-sql: true
  hibernite:
    ddl-auto: none
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn03?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123

eureka:
  client:
    service-url:
      defaultZone: http://eureka8500.com/eureka



