#配置dev环境
spring:
 profiles: dev
 application:
  name: eurekaServer-config

server:
  port: 8400

eureka:
  instance:
    hostname: eureka8400.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8400.com/eureka

#配置test环境
spring:
 profiles: test
 application:
  name: eurekaServer-test

server:
  port: 8400

eureka:
  instance:
    hostname: eureka8400.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8400.com/eureka


